.TH "projektV2" 3 "Wed Jun 10 2020" "Version 1.0" "Projekt_Programowanie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
projektV2
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDB\fP"
.br
.ti -1c
.RI "class \fBLoggedIn\fP"
.br
.ti -1c
.RI "class \fBLogInForm\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBRegisterForm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Projekt_Programowanie from the source code\&.
