.TH "projektV2.RegisterForm" 3 "Wed Jun 10 2020" "Version 1.0" "Projekt_Programowanie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
projektV2.RegisterForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Boolean \fBmatchPIN\fP (string pin)"
.br
.RI "regular expression of PIN field 4 numbers only "
.ti -1c
.RI "Boolean \fBmatchAge\fP (string age)"
.br
.RI "regular expression of age field 4 numbers only "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void projektV2\&.RegisterForm\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SS "Boolean projektV2\&.RegisterForm\&.matchAge (string age)"

.PP
regular expression of age field 4 numbers only 
.PP
\fBParameters\fP
.RS 4
\fIage\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "Boolean projektV2\&.RegisterForm\&.matchPIN (string pin)"

.PP
regular expression of PIN field 4 numbers only 
.PP
\fBParameters\fP
.RS 4
\fIpin\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Projekt_Programowanie from the source code\&.
